# global variables
variables:

# smg config
conf:
  usage: 高度可定制化命令行工具
  desc: 高度可定制化命令行工具, 支持 mysql、http、shell 等。
  echoAddress: "127.0.0.1:11111"
  tableLen: 
  subCommandLen: 

# logger
logger:
  level: debug
# remote registry config 
registry:
  provider: 'consul'
  address: ''
  token: ''
  prefix: 'test'